// <auto-generated />
namespace ALISS.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class organisation_claimed_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(organisation_claimed_date));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071453041_organisation_claimed_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
