// <auto-generated />
namespace ALISS.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Service_Claimed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Service_Claimed));
        
        string IMigrationMetadata.Id
        {
            get { return "202303011219212_Service_Claimed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
