# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alissuser',
            name='username',
        ),
        migrations.AddField(
            model_name='alissuser',
            name='accept_privacy_policy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alissuser',
            name='accept_terms_and_conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alissuser',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alissuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='alissuser',
            name='postcode',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
