# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def delete_problems(apps, schema_editor):
        ServiceProblem = apps.get_model('aliss', 'ServiceProblem')
        ServiceProblem.objects.all().delete()

    dependencies = [
        ('aliss', '0005_recommendedservicelist'),
    ]

    operations = [
        migrations.RunPython(delete_problems),
    ]
