# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0006_auto_20180126_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceproblem',
            name='email',
        ),
        migrations.AddField(
            model_name='serviceproblem',
            name='type',
            field=models.IntegerField(choices=[(0, 'Information provided is unclear'), (10, 'Contact information incorrect or no response'), (20, 'This service no longer exists'), (30, 'This service does not operate in my area')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceproblem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendedservicelist',
            name='services',
            field=models.ManyToManyField(blank=True, to='aliss.Service'),
        ),
    ]
