# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0007_auto_20180126_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='alissuser',
            name='helpful_services',
            field=models.ManyToManyField(blank=True, related_name='helped_users', to='aliss.Service'),
        ),
        migrations.AlterField(
            model_name='serviceproblem',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
