# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0008_auto_20180129_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
