# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0010_alissuser_prepopulate_postcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alissuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='alissuser',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
