# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0011_auto_20180222_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alissuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.IntegerField(choices=[(0, 'Un-reviewed'), (10, 'Confirmed'), (20, 'Denied'), (30, 'Revoked')], default=0),
        ),
    ]
