# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-03 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0014_remove_claim_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='digest_selections', to='aliss.Category')),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliss.Postcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='aliss.Category'),
        ),
    ]
