# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0014_remove_claim_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(related_name='services', to='aliss.Category'),
        ),
    ]
