# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0015_auto_20180903_1448'),
        ('aliss', '0015_auto_20180910_1137'),
    ]

    operations = [
    ]
