# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-21 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0016_merge_20180917_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestselection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digest_selections', to='aliss.Category'),
        ),
    ]
