# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0017_auto_20180921_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='email',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='phone',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.URLField(blank=True, verbose_name='Web address'),
        ),
    ]
