# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0018_auto_20181116_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
