# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0020_service_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
