# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 13:25
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0020_auto_20181126_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
