# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 13:19
from __future__ import unicode_literals

import aliss.models.aliss_cloudinary
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0022_auto_20181213_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=aliss.models.aliss_cloudinary.ALISSCloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
