# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0023_auto_20181219_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='place_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
