# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0024_postcode_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='place_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
