# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 11:28
from __future__ import unicode_literals

import aliss.models.postcode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0026_auto_20190501_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='slug',
            field=models.SlugField(default=aliss.models.postcode.generate_place_name_slug),
        ),
    ]
