# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-17 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0027_postcode_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
            ],
        ),
    ]
