# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aliss', '0028_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=140)),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=140)),
                ('for_organisations', models.BooleanField(default=True)),
                ('for_services', models.BooleanField(default=True)),
                ('for_locations', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignedproperty',
            name='property_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_properties', to='aliss.Property'),
        ),
    ]
