# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-01 11:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0028_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='phone',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
