# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0028_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='alissuser',
            name='Email_two',
            field=models.EmailField(default=django.utils.datetime_safe.date.today, error_messages={'unique': 'A user with that email address already exists.'}, max_length=254),
            preserve_default=False,
        ),
    ]
