# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-30 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0028_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
