# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0029_alissuser_email_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alissuser',
            name='email_two',
        ),
        migrations.AddField(
            model_name='alissuser',
            name='email_two',
            field=models.EmailField(default=datetime.datetime(2020, 5, 17, 17, 50, 14, 283784, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
