# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-08 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0029_auto_20191217_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='icon',
            field=models.CharField(default='fa fa-square', max_length=100),
        ),
    ]
