# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-01-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0030_property_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='icon',
            field=models.CharField(default='fa fa-circle', max_length=100),
        ),
    ]
