# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-01 11:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0030_auto_20200701_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 11', regex='^.{11}$')]),
        ),
    ]
