# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0031_auto_20200517_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alissuser',
            name='email_two',
            field=models.CharField(max_length=50),
        ),
    ]
