# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0032_auto_20200517_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alissuser',
            name='email_two',
            field=models.EmailField(max_length=50),
        ),
    ]
