# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0033_auto_20200517_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alissuser',
            name='email_two',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True),
        ),
    ]
