# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-18 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0034_auto_20200517_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alissuser',
            name='email_two',
        ),
    ]
