# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-08 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0035_auto_20200708_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
