# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-10 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0038_remove_claim_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='service',
            field=models.ForeignKey(default=(datetime.datetime(2020, 6, 10, 9, 33, 2, 550391, tzinfo=utc),), on_delete=django.db.models.deletion.CASCADE, to='aliss.Service'),
            preserve_default=False,
        ),
    ]
