# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-09 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0040_auto_20200709_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
