# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0041_remove_claim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='name',
            field=models.CharField(default='Name Missing', max_length=100),
        ),
    ]
