# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-15 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0043_auto_20200714_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be max.13', regex='^.{13}$')]),
        ),
    ]
