# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-16 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0046_auto_20200715_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
