# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0048_claim_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
