# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-07-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0049_auto_20200716_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
    ]
