# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-10 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0051_claim_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='service',
        ),
    ]
