# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliss', '0052_remove_claim_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aliss.Service'),
        ),
    ]
