//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasDataGovernance"
	/// <summary>Has Data Governance</summary>
	public partial interface ICdtHasDataGovernance : IPublishedElement
	{
		/// <summary>Bulk Review Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		int BulkReviewMonths { get; }

		/// <summary>Data Disclaimer</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string DataDisclaimer { get; }

		/// <summary>Email 1 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		int Email1NotificationMonths { get; }

		/// <summary>Email 2 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		int Email2NotificationMonths { get; }

		/// <summary>Email 3 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		int Email3NotificationMonths { get; }
	}

	/// <summary>Has Data Governance</summary>
	[PublishedModel("cdtHasDataGovernance")]
	public partial class CdtHasDataGovernance : PublishedElementModel, ICdtHasDataGovernance
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasDataGovernance";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasDataGovernance, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasDataGovernance(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Bulk Review Months: How many months ahead should an email include?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("bulkReviewMonths")]
		public virtual int BulkReviewMonths => GetBulkReviewMonths(this);

		/// <summary>Static getter for Bulk Review Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static int GetBulkReviewMonths(ICdtHasDataGovernance that) => that.Value<int>("bulkReviewMonths");

		///<summary>
		/// Data Disclaimer: A message to be displayed below the services page filters detailing the review process and data moved to the end of the search results.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("dataDisclaimer")]
		public virtual string DataDisclaimer => GetDataDisclaimer(this);

		/// <summary>Static getter for Data Disclaimer</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetDataDisclaimer(ICdtHasDataGovernance that) => that.Value<string>("dataDisclaimer");

		///<summary>
		/// Email 1 Notification Months: How many months since last review will the first email be sent?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("email1NotificationMonths")]
		public virtual int Email1NotificationMonths => GetEmail1NotificationMonths(this);

		/// <summary>Static getter for Email 1 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static int GetEmail1NotificationMonths(ICdtHasDataGovernance that) => that.Value<int>("email1NotificationMonths");

		///<summary>
		/// Email 2 Notification Months: How many months since the first email will the second email be sent?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("email2NotificationMonths")]
		public virtual int Email2NotificationMonths => GetEmail2NotificationMonths(this);

		/// <summary>Static getter for Email 2 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static int GetEmail2NotificationMonths(ICdtHasDataGovernance that) => that.Value<int>("email2NotificationMonths");

		///<summary>
		/// Email 3 Notification Months: How many months since the second email will the third email be sent?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("email3NotificationMonths")]
		public virtual int Email3NotificationMonths => GetEmail3NotificationMonths(this);

		/// <summary>Static getter for Email 3 Notification Months</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static int GetEmail3NotificationMonths(ICdtHasDataGovernance that) => that.Value<int>("email3NotificationMonths");
	}
}
