//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasServiceConfiguration"
	/// <summary>Has Service Configuration</summary>
	public partial interface ICdtHasServiceConfiguration : IPublishedElement
	{
		/// <summary>Actions Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString ServiceActionsCopy { get; }

		/// <summary>Actions Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string ServiceActionsTitle { get; }

		/// <summary>Contact Info Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString ServiceContactInfoCopy { get; }

		/// <summary>Contact Info Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string ServiceContactInfoTitle { get; }

		/// <summary>Improve Listing Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString ServiceImproveListingCopy { get; }

		/// <summary>Improve Listing Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string ServiceImproveListingTitle { get; }
	}

	/// <summary>Has Service Configuration</summary>
	[PublishedModel("cdtHasServiceConfiguration")]
	public partial class CdtHasServiceConfiguration : PublishedElementModel, ICdtHasServiceConfiguration
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasServiceConfiguration";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasServiceConfiguration, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasServiceConfiguration(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Actions Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceActionsCopy")]
		public virtual global::System.Web.IHtmlString ServiceActionsCopy => GetServiceActionsCopy(this);

		/// <summary>Static getter for Actions Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetServiceActionsCopy(ICdtHasServiceConfiguration that) => that.Value<global::System.Web.IHtmlString>("serviceActionsCopy");

		///<summary>
		/// Actions Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceActionsTitle")]
		public virtual string ServiceActionsTitle => GetServiceActionsTitle(this);

		/// <summary>Static getter for Actions Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetServiceActionsTitle(ICdtHasServiceConfiguration that) => that.Value<string>("serviceActionsTitle");

		///<summary>
		/// Contact Info Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceContactInfoCopy")]
		public virtual global::System.Web.IHtmlString ServiceContactInfoCopy => GetServiceContactInfoCopy(this);

		/// <summary>Static getter for Contact Info Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetServiceContactInfoCopy(ICdtHasServiceConfiguration that) => that.Value<global::System.Web.IHtmlString>("serviceContactInfoCopy");

		///<summary>
		/// Contact Info Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceContactInfoTitle")]
		public virtual string ServiceContactInfoTitle => GetServiceContactInfoTitle(this);

		/// <summary>Static getter for Contact Info Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetServiceContactInfoTitle(ICdtHasServiceConfiguration that) => that.Value<string>("serviceContactInfoTitle");

		///<summary>
		/// Improve Listing Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceImproveListingCopy")]
		public virtual global::System.Web.IHtmlString ServiceImproveListingCopy => GetServiceImproveListingCopy(this);

		/// <summary>Static getter for Improve Listing Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetServiceImproveListingCopy(ICdtHasServiceConfiguration that) => that.Value<global::System.Web.IHtmlString>("serviceImproveListingCopy");

		///<summary>
		/// Improve Listing Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("serviceImproveListingTitle")]
		public virtual string ServiceImproveListingTitle => GetServiceImproveListingTitle(this);

		/// <summary>Static getter for Improve Listing Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetServiceImproveListingTitle(ICdtHasServiceConfiguration that) => that.Value<string>("serviceImproveListingTitle");
	}
}
