//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasSearchEngineOptimisation"
	/// <summary>Has Search Engine Optimisation</summary>
	public partial interface ICdtHasSearchEngineOptimisation : IPublishedContent
	{
		/// <summary>Hide children from Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		bool HideChildrenFromSitemap { get; }

		/// <summary>Hide from Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		bool HideFromSitemap { get; }

		/// <summary>Open Graph Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Core.Models.MediaWithCrops OpenGraphImage { get; }

		/// <summary>Open Graph Page Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string OpenGraphPageDescription { get; }

		/// <summary>Open Graph Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string OpenGraphPageTitle { get; }

		/// <summary>Robots "No Follow"</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		bool RobotsNoFollow { get; }

		/// <summary>Robots "No Index"</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		bool RobotsNoIndex { get; }

		/// <summary>SEO Page Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string SeoPageDescription { get; }

		/// <summary>SEO Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string SeoPageTitle { get; }
	}

	/// <summary>Has Search Engine Optimisation</summary>
	[PublishedModel("cdtHasSearchEngineOptimisation")]
	public partial class CdtHasSearchEngineOptimisation : PublishedContentModel, ICdtHasSearchEngineOptimisation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasSearchEngineOptimisation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasSearchEngineOptimisation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasSearchEngineOptimisation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Hide children from Sitemap: This node's children will be excluded from the generated sitemap, regardless of their individual setting
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("hideChildrenFromSitemap")]
		public virtual bool HideChildrenFromSitemap => GetHideChildrenFromSitemap(this);

		/// <summary>Static getter for Hide children from Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static bool GetHideChildrenFromSitemap(ICdtHasSearchEngineOptimisation that) => that.Value<bool>("hideChildrenFromSitemap");

		///<summary>
		/// Hide from Sitemap: This node will be excluded form the generated sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => GetHideFromSitemap(this);

		/// <summary>Static getter for Hide from Sitemap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static bool GetHideFromSitemap(ICdtHasSearchEngineOptimisation that) => that.Value<bool>("hideFromSitemap");

		///<summary>
		/// Open Graph Image: The image used for Open Graph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops OpenGraphImage => GetOpenGraphImage(this);

		/// <summary>Static getter for Open Graph Image</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetOpenGraphImage(ICdtHasSearchEngineOptimisation that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("openGraphImage");

		///<summary>
		/// Open Graph Page Description: The page description for Open Graph (If blank, SEO Page Description will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphPageDescription")]
		public virtual string OpenGraphPageDescription => GetOpenGraphPageDescription(this);

		/// <summary>Static getter for Open Graph Page Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetOpenGraphPageDescription(ICdtHasSearchEngineOptimisation that) => that.Value<string>("openGraphPageDescription");

		///<summary>
		/// Open Graph Page Title: The page title for Open Graph (If blank, SEO Page Title will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphPageTitle")]
		public virtual string OpenGraphPageTitle => GetOpenGraphPageTitle(this);

		/// <summary>Static getter for Open Graph Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetOpenGraphPageTitle(ICdtHasSearchEngineOptimisation that) => that.Value<string>("openGraphPageTitle");

		///<summary>
		/// Robots "No Follow": Prevent Google from following links on this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("robotsNoFollow")]
		public virtual bool RobotsNoFollow => GetRobotsNoFollow(this);

		/// <summary>Static getter for Robots "No Follow"</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static bool GetRobotsNoFollow(ICdtHasSearchEngineOptimisation that) => that.Value<bool>("robotsNoFollow");

		///<summary>
		/// Robots "No Index": Exclude this page from Google search results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("robotsNoIndex")]
		public virtual bool RobotsNoIndex => GetRobotsNoIndex(this);

		/// <summary>Static getter for Robots "No Index"</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static bool GetRobotsNoIndex(ICdtHasSearchEngineOptimisation that) => that.Value<bool>("robotsNoIndex");

		///<summary>
		/// SEO Page Description: The page description for SEO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("seoPageDescription")]
		public virtual string SeoPageDescription => GetSeoPageDescription(this);

		/// <summary>Static getter for SEO Page Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetSeoPageDescription(ICdtHasSearchEngineOptimisation that) => that.Value<string>("seoPageDescription");

		///<summary>
		/// SEO Page Title: The page title for SEO (If blank, Page Title will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("seoPageTitle")]
		public virtual string SeoPageTitle => GetSeoPageTitle(this);

		/// <summary>Static getter for SEO Page Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetSeoPageTitle(ICdtHasSearchEngineOptimisation that) => that.Value<string>("seoPageTitle");
	}
}
