//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasSearchFilters"
	/// <summary>Has Search Filters</summary>
	public partial interface ICdtHasSearchFilters : IPublishedElement
	{
		/// <summary>What Label Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string WhatLabelText { get; }

		/// <summary>What Placeholder Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string WhatPlaceholderText { get; }

		/// <summary>Where Label Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string WhereLabelText { get; }

		/// <summary>Where Placeholder Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string WherePlaceholderText { get; }
	}

	/// <summary>Has Search Filters</summary>
	[PublishedModel("cdtHasSearchFilters")]
	public partial class CdtHasSearchFilters : PublishedElementModel, ICdtHasSearchFilters
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasSearchFilters";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasSearchFilters, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasSearchFilters(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// What Label Text: Text to be shown above the filter text field.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("whatLabelText")]
		public virtual string WhatLabelText => GetWhatLabelText(this);

		/// <summary>Static getter for What Label Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetWhatLabelText(ICdtHasSearchFilters that) => that.Value<string>("whatLabelText");

		///<summary>
		/// What Placeholder Text: Text to be shown inside the filter text field when blank.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("whatPlaceholderText")]
		public virtual string WhatPlaceholderText => GetWhatPlaceholderText(this);

		/// <summary>Static getter for What Placeholder Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetWhatPlaceholderText(ICdtHasSearchFilters that) => that.Value<string>("whatPlaceholderText");

		///<summary>
		/// Where Label Text: Text to be shown above the filter text field.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("whereLabelText")]
		public virtual string WhereLabelText => GetWhereLabelText(this);

		/// <summary>Static getter for Where Label Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetWhereLabelText(ICdtHasSearchFilters that) => that.Value<string>("whereLabelText");

		///<summary>
		/// Where Placeholder Text: Text to be shown inside the filter text field when blank.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("wherePlaceholderText")]
		public virtual string WherePlaceholderText => GetWherePlaceholderText(this);

		/// <summary>Static getter for Where Placeholder Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetWherePlaceholderText(ICdtHasSearchFilters that) => that.Value<string>("wherePlaceholderText");
	}
}
