//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasFormContent"
	/// <summary>Has Form Content</summary>
	public partial interface ICdtHasFormContent : IPublishedElement
	{
		/// <summary>Form Body Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString FormBodyText { get; }

		/// <summary>Privicy Statement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString PrivicyStatement { get; }
	}

	/// <summary>Has Form Content</summary>
	[PublishedModel("cdtHasFormContent")]
	public partial class CdtHasFormContent : PublishedElementModel, ICdtHasFormContent
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasFormContent";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasFormContent, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasFormContent(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Form Body Text: Content to be shown after the form but before the submit button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("formBodyText")]
		public virtual global::System.Web.IHtmlString FormBodyText => GetFormBodyText(this);

		/// <summary>Static getter for Form Body Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetFormBodyText(ICdtHasFormContent that) => that.Value<global::System.Web.IHtmlString>("formBodyText");

		///<summary>
		/// Privicy Statement: Text shown at the bottom of the form directing users to the privacy policy.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("privicyStatement")]
		public virtual global::System.Web.IHtmlString PrivicyStatement => GetPrivicyStatement(this);

		/// <summary>Static getter for Privicy Statement</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetPrivicyStatement(ICdtHasFormContent that) => that.Value<global::System.Web.IHtmlString>("privicyStatement");
	}
}
