//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasOrganisationConfiguration"
	/// <summary>Has Organisation Configuration</summary>
	public partial interface ICdtHasOrganisationConfiguration : IPublishedElement
	{
		/// <summary>Actions Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString OrganisationActionsCopy { get; }

		/// <summary>Actions Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string OrganisationActionsTitle { get; }

		/// <summary>Contact Info Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString OrganisationContactInfoCopy { get; }

		/// <summary>Contact Info Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string OrganisationContactInfoTitle { get; }

		/// <summary>Improve Listing Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Web.IHtmlString OrganisationImproveListingCopy { get; }

		/// <summary>Improve Listing Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string OrganisationImproveListingTitle { get; }
	}

	/// <summary>Has Organisation Configuration</summary>
	[PublishedModel("cdtHasOrganisationConfiguration")]
	public partial class CdtHasOrganisationConfiguration : PublishedElementModel, ICdtHasOrganisationConfiguration
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasOrganisationConfiguration";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasOrganisationConfiguration, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasOrganisationConfiguration(IPublishedElement content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Actions Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationActionsCopy")]
		public virtual global::System.Web.IHtmlString OrganisationActionsCopy => GetOrganisationActionsCopy(this);

		/// <summary>Static getter for Actions Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetOrganisationActionsCopy(ICdtHasOrganisationConfiguration that) => that.Value<global::System.Web.IHtmlString>("organisationActionsCopy");

		///<summary>
		/// Actions Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationActionsTitle")]
		public virtual string OrganisationActionsTitle => GetOrganisationActionsTitle(this);

		/// <summary>Static getter for Actions Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetOrganisationActionsTitle(ICdtHasOrganisationConfiguration that) => that.Value<string>("organisationActionsTitle");

		///<summary>
		/// Contact Info Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationContactInfoCopy")]
		public virtual global::System.Web.IHtmlString OrganisationContactInfoCopy => GetOrganisationContactInfoCopy(this);

		/// <summary>Static getter for Contact Info Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetOrganisationContactInfoCopy(ICdtHasOrganisationConfiguration that) => that.Value<global::System.Web.IHtmlString>("organisationContactInfoCopy");

		///<summary>
		/// Contact Info Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationContactInfoTitle")]
		public virtual string OrganisationContactInfoTitle => GetOrganisationContactInfoTitle(this);

		/// <summary>Static getter for Contact Info Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetOrganisationContactInfoTitle(ICdtHasOrganisationConfiguration that) => that.Value<string>("organisationContactInfoTitle");

		///<summary>
		/// Improve Listing Copy
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationImproveListingCopy")]
		public virtual global::System.Web.IHtmlString OrganisationImproveListingCopy => GetOrganisationImproveListingCopy(this);

		/// <summary>Static getter for Improve Listing Copy</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Web.IHtmlString GetOrganisationImproveListingCopy(ICdtHasOrganisationConfiguration that) => that.Value<global::System.Web.IHtmlString>("organisationImproveListingCopy");

		///<summary>
		/// Improve Listing Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("organisationImproveListingTitle")]
		public virtual string OrganisationImproveListingTitle => GetOrganisationImproveListingTitle(this);

		/// <summary>Static getter for Improve Listing Title</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetOrganisationImproveListingTitle(ICdtHasOrganisationConfiguration that) => that.Value<string>("organisationImproveListingTitle");
	}
}
