//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "cdtHasSiteNavigation"
	/// <summary>Has Site Navigation</summary>
	public partial interface ICdtHasSiteNavigation : IPublishedContent
	{
		/// <summary>About Claimed Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent AboutClaimedPage { get; }

		/// <summary>Copyright</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		string Copyright { get; }

		/// <summary>Data Standards PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Core.Models.MediaWithCrops DataStandardsPdf { get; }

		/// <summary>Feedback URL</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Web.Models.Link FeedbackUrl { get; }

		/// <summary>Footer Navigation Columns</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtFooterNavigationColumn> FooterNavigationColumns { get; }

		/// <summary>Header Navigation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> HeaderNavigation { get; }

		/// <summary>Header Navigation Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.HeaderLinkItem> HeaderNavigationItems { get; }

		/// <summary>Privacy Policy PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Core.Models.MediaWithCrops PrivacyPolicyPdf { get; }

		/// <summary>Social Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtSocialLinkItem> SocialLinks { get; }

		/// <summary>Terms & Conditions PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		global::Umbraco.Core.Models.MediaWithCrops TermsConditionsPdf { get; }
	}

	/// <summary>Has Site Navigation</summary>
	[PublishedModel("cdtHasSiteNavigation")]
	public partial class CdtHasSiteNavigation : PublishedContentModel, ICdtHasSiteNavigation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "cdtHasSiteNavigation";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CdtHasSiteNavigation, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CdtHasSiteNavigation(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// About Claimed Page: Select the page that will be linked to from the claims disclaimer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("aboutClaimedPage")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent AboutClaimedPage => GetAboutClaimedPage(this);

		/// <summary>Static getter for About Claimed Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetAboutClaimedPage(ICdtHasSiteNavigation that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("aboutClaimedPage");

		///<summary>
		/// Copyright
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("copyright")]
		public virtual string Copyright => GetCopyright(this);

		/// <summary>Static getter for Copyright</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static string GetCopyright(ICdtHasSiteNavigation that) => that.Value<string>("copyright");

		///<summary>
		/// Data Standards PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("dataStandardsPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DataStandardsPdf => GetDataStandardsPdf(this);

		/// <summary>Static getter for Data Standards PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetDataStandardsPdf(ICdtHasSiteNavigation that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("dataStandardsPdf");

		///<summary>
		/// Feedback URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("feedbackUrl")]
		public virtual global::Umbraco.Web.Models.Link FeedbackUrl => GetFeedbackUrl(this);

		/// <summary>Static getter for Feedback URL</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Web.Models.Link GetFeedbackUrl(ICdtHasSiteNavigation that) => that.Value<global::Umbraco.Web.Models.Link>("feedbackUrl");

		///<summary>
		/// Footer Navigation Columns
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("footerNavigationColumns")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtFooterNavigationColumn> FooterNavigationColumns => GetFooterNavigationColumns(this);

		/// <summary>Static getter for Footer Navigation Columns</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtFooterNavigationColumn> GetFooterNavigationColumns(ICdtHasSiteNavigation that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtFooterNavigationColumn>>("footerNavigationColumns");

		///<summary>
		/// Header Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("headerNavigation")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> HeaderNavigation => GetHeaderNavigation(this);

		/// <summary>Static getter for Header Navigation</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> GetHeaderNavigation(ICdtHasSiteNavigation that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link>>("headerNavigation");

		///<summary>
		/// Header Navigation Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("headerNavigationItems")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.HeaderLinkItem> HeaderNavigationItems => GetHeaderNavigationItems(this);

		/// <summary>Static getter for Header Navigation Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.HeaderLinkItem> GetHeaderNavigationItems(ICdtHasSiteNavigation that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.HeaderLinkItem>>("headerNavigationItems");

		///<summary>
		/// Privacy Policy PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("privacyPolicyPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops PrivacyPolicyPdf => GetPrivacyPolicyPdf(this);

		/// <summary>Static getter for Privacy Policy PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetPrivacyPolicyPdf(ICdtHasSiteNavigation that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("privacyPolicyPdf");

		///<summary>
		/// Social Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("socialLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtSocialLinkItem> SocialLinks => GetSocialLinks(this);

		/// <summary>Static getter for Social Links</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtSocialLinkItem> GetSocialLinks(ICdtHasSiteNavigation that) => that.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtSocialLinkItem>>("socialLinks");

		///<summary>
		/// Terms & Conditions PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("termsConditionsPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops TermsConditionsPdf => GetTermsConditionsPdf(this);

		/// <summary>Static getter for Terms & Conditions PDF</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static global::Umbraco.Core.Models.MediaWithCrops GetTermsConditionsPdf(ICdtHasSiteNavigation that) => that.Value<global::Umbraco.Core.Models.MediaWithCrops>("termsConditionsPdf");
	}
}
