// <auto-generated />
namespace ALISS.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class audits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(audits));
        
        string IMigrationMetadata.Id
        {
            get { return "202110051101338_audits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
