//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Save This Service</summary>
	[PublishedModel("dtSaveThisService")]
	public partial class DtSaveThisService : PublishedContentModel, ICdtHasContent, ICdtHasFormContent, ICdtHasPageTitle, ICdtHasSearchEngineOptimisation, ICdtHasSentMessage, ICdtHasSiteNavigation
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const string ModelTypeAlias = "dtSaveThisService";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DtSaveThisService, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public DtSaveThisService(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Body Text: Main content of the page To enter a new line rather than a new paragraph, press shift + enter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("bodyText")]
		public virtual global::System.Web.IHtmlString BodyText => global::Umbraco.Web.PublishedModels.CdtHasContent.GetBodyText(this);

		///<summary>
		/// Form Body Text: Content to be shown after the form but before the submit button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("formBodyText")]
		public virtual global::System.Web.IHtmlString FormBodyText => global::Umbraco.Web.PublishedModels.CdtHasFormContent.GetFormBodyText(this);

		///<summary>
		/// Privicy Statement: Text shown at the bottom of the form directing users to the privacy policy.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("privicyStatement")]
		public virtual global::System.Web.IHtmlString PrivicyStatement => global::Umbraco.Web.PublishedModels.CdtHasFormContent.GetPrivicyStatement(this);

		///<summary>
		/// Title: The page title, shown at the top of the page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("title")]
		public virtual string Title => global::Umbraco.Web.PublishedModels.CdtHasPageTitle.GetTitle(this);

		///<summary>
		/// Hide children from Sitemap: This node's children will be excluded from the generated sitemap, regardless of their individual setting
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("hideChildrenFromSitemap")]
		public virtual bool HideChildrenFromSitemap => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetHideChildrenFromSitemap(this);

		///<summary>
		/// Hide from Sitemap: This node will be excluded form the generated sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("hideFromSitemap")]
		public virtual bool HideFromSitemap => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetHideFromSitemap(this);

		///<summary>
		/// Open Graph Image: The image used for Open Graph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphImage")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops OpenGraphImage => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetOpenGraphImage(this);

		///<summary>
		/// Open Graph Page Description: The page description for Open Graph (If blank, SEO Page Description will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphPageDescription")]
		public virtual string OpenGraphPageDescription => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetOpenGraphPageDescription(this);

		///<summary>
		/// Open Graph Page Title: The page title for Open Graph (If blank, SEO Page Title will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("openGraphPageTitle")]
		public virtual string OpenGraphPageTitle => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetOpenGraphPageTitle(this);

		///<summary>
		/// Robots "No Follow": Prevent Google from following links on this page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("robotsNoFollow")]
		public virtual bool RobotsNoFollow => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetRobotsNoFollow(this);

		///<summary>
		/// Robots "No Index": Exclude this page from Google search results
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("robotsNoIndex")]
		public virtual bool RobotsNoIndex => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetRobotsNoIndex(this);

		///<summary>
		/// SEO Page Description: The page description for SEO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("seoPageDescription")]
		public virtual string SeoPageDescription => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetSeoPageDescription(this);

		///<summary>
		/// SEO Page Title: The page title for SEO (If blank, Page Title will be used)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("seoPageTitle")]
		public virtual string SeoPageTitle => global::Umbraco.Web.PublishedModels.CdtHasSearchEngineOptimisation.GetSeoPageTitle(this);

		///<summary>
		/// Sent Body Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("sentBodyText")]
		public virtual global::System.Web.IHtmlString SentBodyText => global::Umbraco.Web.PublishedModels.CdtHasSentMessage.GetSentBodyText(this);

		///<summary>
		/// About Claimed Page: Select the page that will be linked to from the claims disclaimer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("aboutClaimedPage")]
		public virtual global::Umbraco.Core.Models.PublishedContent.IPublishedContent AboutClaimedPage => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetAboutClaimedPage(this);

		///<summary>
		/// Copyright
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("copyright")]
		public virtual string Copyright => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetCopyright(this);

		///<summary>
		/// Data Standards PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("dataStandardsPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops DataStandardsPdf => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetDataStandardsPdf(this);

		///<summary>
		/// Feedback URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("feedbackUrl")]
		public virtual global::Umbraco.Web.Models.Link FeedbackUrl => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetFeedbackUrl(this);

		///<summary>
		/// Footer Navigation Columns
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("footerNavigationColumns")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtFooterNavigationColumn> FooterNavigationColumns => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetFooterNavigationColumns(this);

		///<summary>
		/// Header Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("headerNavigation")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> HeaderNavigation => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetHeaderNavigation(this);

		///<summary>
		/// Header Navigation Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("headerNavigationItems")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.HeaderLinkItem> HeaderNavigationItems => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetHeaderNavigationItems(this);

		///<summary>
		/// Privacy Policy PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("privacyPolicyPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops PrivacyPolicyPdf => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetPrivacyPolicyPdf(this);

		///<summary>
		/// Social Links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("socialLinks")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.CdtSocialLinkItem> SocialLinks => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetSocialLinks(this);

		///<summary>
		/// Terms & Conditions PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.3")]
		[ImplementPropertyType("termsConditionsPdf")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops TermsConditionsPdf => global::Umbraco.Web.PublishedModels.CdtHasSiteNavigation.GetTermsConditionsPdf(this);
	}
}
